# Generated by Django 6.0.6 on 2026-07-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputadorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=150, verbose_name='Nome do usuário')),
                ('ip_computador', models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='IP do computador')),
                ('mac_address', models.CharField(max_length=17, unique=True, verbose_name='Endereço MAC')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Usuário de computador',
                'verbose_name_plural': 'Usuários de computadores',
                'ordering': ['nome_usuario'],
            },
        ),
    ]
