# Generated by Django 6.0.6 on 2026-07-04 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_setor_computadorusuario_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('desktop', 'Desktop'), ('notebook', 'Notebook'), ('impressora', 'Impressora'), ('monitor', 'Monitor'), ('roteador', 'Roteador'), ('switch', 'Switch'), ('nobreak', 'Nobreak'), ('celular', 'Celular'), ('tablet', 'Tablet'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo do equipamento')),
                ('patrimonio', models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='Patrimônio')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=120, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Número de série')),
                ('usuario_responsavel', models.CharField(blank=True, max_length=150, verbose_name='Usuário responsável')),
                ('status', models.CharField(choices=[('em_uso', 'Em uso'), ('estoque', 'Em estoque'), ('manutencao', 'Em manutenção'), ('inativo', 'Baixado/Inativo')], default='em_uso', max_length=30, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='inventario.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['tipo', 'marca', 'modelo'],
            },
        ),
    ]
