# Generated by Django 6.0.6 on 2026-07-04 22:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_equipamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManutencaoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ocorrencia', models.CharField(choices=[('manutencao', 'Manutenção'), ('troca_peca', 'Troca de peça'), ('formatacao', 'Formatação'), ('limpeza', 'Limpeza'), ('instalacao_software', 'Instalação de software'), ('baixa', 'Baixa'), ('movimentacao', 'Movimentação de setor'), ('observacao', 'Observação geral')], default='manutencao', max_length=40, verbose_name='Tipo de ocorrência')),
                ('data_ocorrencia', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da ocorrência')),
                ('responsavel_atendimento', models.CharField(blank=True, max_length=150, verbose_name='Responsável pelo atendimento')),
                ('descricao', models.TextField(verbose_name='Descrição do serviço')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=30, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='inventario.equipamento', verbose_name='Equipamento')),
            ],
            options={
                'verbose_name': 'Histórico/Manutenção',
                'verbose_name_plural': 'Históricos/Manutenções',
                'ordering': ['-data_ocorrencia', '-criado_em'],
            },
        ),
    ]
