# Generated by Django 6.0.6 on 2026-07-04 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_manutencaoequipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='data_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Data de compra'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='garantia_ate',
            field=models.DateField(blank=True, null=True, verbose_name='Garantia até'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='numero_nota_fiscal',
            field=models.CharField(blank=True, max_length=80, verbose_name='Número da nota fiscal'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='origem',
            field=models.CharField(blank=True, choices=[('compra', 'Compra'), ('doacao', 'Doação'), ('transferencia', 'Transferência'), ('reaproveitamento', 'Reaproveitamento')], max_length=30, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='produto_novo',
            field=models.BooleanField(default=False, verbose_name='Produto novo'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='valor_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de compra'),
        ),
        migrations.CreateModel(
            name='EquipamentoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='equipamentos/fotos/%Y/%m/', verbose_name='Foto')),
                ('descricao', models.CharField(blank=True, max_length=150, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inventario.equipamento', verbose_name='Equipamento')),
            ],
            options={
                'verbose_name': 'Foto do equipamento',
                'verbose_name_plural': 'Fotos dos equipamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
