# Generated by Django 6.0.6 on 2026-07-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_equipamento_data_compra_equipamento_fornecedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadorusuario',
            name='armazenamento_capacidade',
            field=models.CharField(blank=True, max_length=80, verbose_name='Capacidade do armazenamento'),
        ),
        migrations.AddField(
            model_name='computadorusuario',
            name='armazenamento_tipo',
            field=models.CharField(blank=True, choices=[('ssd', 'SSD'), ('hd', 'HD'), ('ssd_hd', 'SSD + HD'), ('nvme', 'NVMe'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo de armazenamento'),
        ),
        migrations.AddField(
            model_name='computadorusuario',
            name='fonte_watts',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fonte em watts'),
        ),
        migrations.AddField(
            model_name='computadorusuario',
            name='memoria_ram',
            field=models.CharField(blank=True, max_length=80, verbose_name='Memória RAM'),
        ),
        migrations.AddField(
            model_name='computadorusuario',
            name='mostrar_especificacoes',
            field=models.BooleanField(default=False, verbose_name='Usar especificações'),
        ),
        migrations.AddField(
            model_name='computadorusuario',
            name='processador',
            field=models.CharField(blank=True, max_length=150, verbose_name='Processador'),
        ),
    ]
