# Generated by Django 6.0.6 on 2026-07-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_computadorusuario_armazenamento_capacidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='tipo_outro_descricao',
            field=models.CharField(blank=True, max_length=120, verbose_name='Descrição do tipo quando outro'),
        ),
    ]
